### ISSUE TITLE
change favicon?

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/oeps-explorer#5]
It looks like the current favicon for this site is a slight modification of the GeoDaCenter logo. Should this be updated? I don't know what it would it be changed to (presumably something more specific to the OEPS project?), so I just wanted to raise the question here.

**Comment by Makosak** [comment]
I like this idea. Potentially using the image from OEPS in progress? 
![image](https://github.com/healthyregions/oeps-explorer/assets/4277692/f5e29d7c-9146-4601-9396-187c6e105745)
